config/routes.rb
Rails.application.routes.draw do
  resources :locks, only: [:update]
  resources :promobars do
    get '/script' => 'promobars#script', :on => :collection
    resource :subheader
  end
  put '/update_promobars_settings', to: "promobars#update_settings"
  get '/script' => 'script#script' 
  root :to => 'home#index'

  mount ShopifyApp::Engine, at: '/'

end

app/controllers/home_controller.rb
class HomeController < AuthenticatedController
  # GET /promobars
  # GET /promobars.json
  def index
    @promobars = Promobar.where(:shop_domain => params[:shop])
    @only_on_index = @promobars.first.only_on_index
    @headers = @promobars.where("bar_type = 1").order(:order_number)
    @footers = @promobars.where("bar_type = 2").order(:order_number)
    
    @headers_on = @promobars.where(promobar_show: true, bar_type: 1).order(:order_number)
    @headers_off = @promobars.where(promobar_show: false, bar_type: 1)
    @footers_on = @promobars.where(promobar_show: true, bar_type: 2).order(:order_number)
    @footers_off = @promobars.where(promobar_show: false, bar_type: 2)
    
    1.upto(@footers_on.count) do |i|
      @footers_on[i-1].order_number = i 
      @footers_on[i-1].save
    end

    1.upto(@footers_off.count) do |i|
      @footers_off[i-1].order_number = 1000 
      @footers_off[i-1].save
    end

    1.upto(@headers_on.count) do |i|
      @headers_on[i-1].order_number = i
      @headers_on[i-1].save
    end
    
    1.upto(@headers_off.count) do |i|
      @headers_off[i-1].order_number = 1000
      @headers_off[i-1].save
    end
    
    scripts = ShopifyAPI::ScriptTag.all
    @counter = scripts.count

    if @promobars.any?
      unless scripts.any?
        script = ShopifyAPI::ScriptTag.new
        script.event = "onload"
        script.src = script_url(:protocol => 'https', :shop => params[:shop])
        script.save

        @counter = '1'
      end
    end
    
    @lock = Lock.where(shop_domain: params[:shop])[0] || Lock.create(shop_domain: params[:shop])

    @sc = ShopifyAPI::ScriptTag.first || 'No scripts detected'
    render 'index.html.erb'
  end
end

app/views/home/_search.html.erb
<%= form_tag promobars_url, method: :get do %>

    <div class="col-sm-4">
      <%= text_field_tag 'promobar[name]', nil, class: "form-control", placeholder: "Search a promo bar..." %>
    </div>

    <%= submit_tag 'Search', class: 'btn btn-primary' %>

<% end %>

app/views/home/index.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: "Home"
    });
  });
</script>
<script>

function swapRows(row1,row2){
  row1_order_number = row1.find("td:nth-child(2)").text();
  row2_order_number = row2.find("td:nth-child(2)").text();
  row1.find("td:nth-child(2)").text(row2_order_number);
  row2.find("td:nth-child(2)").text(row1_order_number);
  row1.find("td:first").insertBefore(row2.find("td:first"));
  row2.find("td:nth-child(2)").insertBefore(row1.find("td:first"));
  row1.insertBefore(row2);
}

function neededArrows(){
  $("a.up").show();
  $("a.down").show();

  $("tr.off a.up").hide();
  $("tr.off a.down").hide();
  $(".headers-table tr.on:last a.down").hide();
  $(".footers-table tr.on:last a.down").hide();
  
  $("table.headers-table > tbody > tr:first td:first a.up").hide();
  $("table.footers-table > tbody > tr:first td:first a.up").hide();
  $("table.headers-table > tbody > tr:last td:first a.down").hide();
  $("table.footers-table > tbody > tr:last td:first a.down").hide();
}

$(document).ready(function(){
  $("tr.off a.up").hide();
  $("tr.off a.down").hide();
  $(".headers-table tr.on:last a.down").hide();
  $(".footers-table tr.on:last a.down").hide();

  $("table.headers-table > tbody > tr:first td:first a.up").hide();
  $("table.footers-table > tbody > tr:first td:first a.up").hide();
  $("table.headers-table > tbody > tr:last td:first a.down").hide();
  $("table.footers-table > tbody > tr:last td:first a.down").hide();
  $(".up,.down").click(function(){
    var row = $(this).parents("tr:first");
    if ($(this).is(".up")) {
      swapRows(row, row.prev());
    } else {
      swapRows(row.next(), row);
    }
  });
  $("#tabs").tabs();
  
  //lock feature 
  $('.lock_turned_on').bootstrapSwitch();
  
  $('.lock_color').minicolors({
    theme: 'bootstrap'
  });
  
  $('.save_lock_feature').click(function(e){
    e.preventDefault();
    var turned_on = $('.lock_turned_on').bootstrapSwitch("state");
    var color = $('.lock_color').val();
    var disable_transition = $('.lock_disable_transition').prop("checked");
    $.ajax({
      url: "<%= lock_url(protocol: 'https', id: @lock.id) %>",
      method: "POST",
      data: {
        _method: "PUT",
        lock: {
          turned_on: turned_on,
          color: color,
          disable_transition
        }
      },
      success: function(){
        alert("Lock feature parameters were updated")
      }
    })
  })
  
  // show promobars only on index
  $('.only_on_index').bootstrapSwitch();
  
  $('.only_on_index').on('switchChange.bootstrapSwitch', function(event, state) {
    var only_on_index = state;
    var shop_domain = "<%= @promobars.first.shop_domain %>"
    $.ajax({
      url: "<%= update_promobars_settings_url(protocol: 'https') %>",
      method: "POST",
      data: {
        _method: "PUT",
        only_on_index: only_on_index,
        shop_domain: shop_domain
      },
      success: function(){
        alert("Global settings were updated.")
      }
    })
  });
});

$(function() {
  $('.promobar_switcher').bootstrapSwitch();
  return $('.promobar_switcher').on('switchChange.bootstrapSwitch', function(event, state) {
    var id, promobar_show, order_number, banners_on, banner_type
    promobar_show = state;
    var row = $(this).parents("tr:first");
    
    if ($(this).hasClass("header")) {
      banner_type = "headers-table";
    } else
      banner_type = "footers-table";
    rows_on = $('table.'+ banner_type +' tr.on');
    banners_on = rows_on.length;
    
    var last_row = $('table.' + banner_type + ' tr:last');
    if (!state) {
      row.addClass("off");  
      row.removeClass("on"); 
      row.find("td:nth-child(2)").text('-');
      row.insertAfter(last_row);
      $('table.' + banner_type + ' > tbody > tr.on').each(function(i, r) {
        $(r).find("td:nth-child(2)").text(i+1);
      });
        
      
    } else {
      row.addClass("on");  
      row.removeClass("off"); 
      row.find("td:nth-child(2)").text(banners_on + 1);
      if (banners_on != 0) {
        row.insertAfter($('table.'+ banner_type +' tr.on:nth-child('+ banners_on +')'));
      } else {
        row.insertBefore($('table.'+ banner_type +' > tbody > tr:first'));
      }
      
    }

    neededArrows();

    id = $(this).attr("id");
    //order_number = parseInt($('.order_number' + id).text());
    

    order_number = $(this).parents("tr:first").find("td:nth-child(2)").text();
    //alert(order_number);
    //$('.order_number' + id).text(order_number);
    
    $.ajax("/promobars/" + id + ".json", {
      type: 'POST',
      dataType: 'json',
      data: {
        _method: 'PUT',
        "promobar[promobar_show]": promobar_show
      },
      success: function() {
        alert("success");
      }
    });
    $.ajax("/promobars/" + id + "/subheader.json", {
      type: 'POST',
      dataType: 'json',
      data: {
        _method: 'PUT',
        "subheader[promobar_show]": promobar_show
      },
      success: function() {
        alert("success");
      }
    });
  });
});

function saveBannerOrder(){
  row = $("table > tbody > tr").each(function(i, r){
    var id, order_number;
    id = $(r).find(".promobar_switcher").attr("id");
    order_number = $(r).find("td:nth-child(2)").text();
    if (order_number === '-') {
      order_number = 1000;
    } else {
      order_number = parseInt(order_number);
    }
    //alert("order_number " + order_number + " id " + id);
    $.ajax("/promobars/" + id + ".json", {
      type: 'POST',
      dataType: 'json',
      data: {
        _method: 'PUT',
        "promobar[order_number]": order_number
      },
      success: function() {
        alert("success");
      }
    });
    //alert("Banners order updated.");  
  });
  
}

</script>
  
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Promobars Listing</a></li>
    <li><a href="#tabs-2">Promobars Settings</a></li>
  </ul>
  <div id="tabs-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Promo bars</h3>
      </div>
      <div class="panel-body">
        <% if notice %>
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% end %>
        <!--<p>Script counter: <%#= @counter %></p>-->
    
        <%# if @sc.is_a? String %>
          <!--<p><%#= @sc %></p>-->
        <%# else %>
          <!--<p>Script attributes: <%#= @sc.attributes.inspect %></p>-->
        <%# end %>
    
        <table class="table table-bordered table-striped table-hover headers-table" style="text-align:center;">
          <caption style="text-align:center;">
            HEADER BANNERS
          </caption>
          <thead>
          <tr>
            <th></th>
            <th>ORDER NUMBER</th>
            <th>BAR TITLE</th>
            <th>BAR TEXT</th>
            <th>BUTTON</th>
            <th>SUB-HEADER</th>
            <th>DATE</th>
            <th>ON/OFF</th>
          </tr>
          </thead>
    
          <tbody>
          <% @headers_on.each_with_index do |bar, i| %>
            <tr class="<%= bar.promobar_show ? "on" : "off" %>">
              <td>
                <a href="#" class="up">Up</a>
                <a href="#" class="down">Down</a>
              </td>
              <td class="order_number<%= bar.id %> order"><%= bar.order_number %></td>
              <td><%= link_to bar.name, edit_promobar_path(bar, :shop_domain => params[:shop]) %></td>
              <td><%= render html: bar.text.html_safe %></td>
              <td><%= bar.button_on ? "YES" : "NO"%></td>
              <td><%= bar.subheader.promobar_show ? "YES" : "NO" unless bar.subheader.nil? %></td> 
              <td ><%= bar.updated_at == bar.created_at ? 'Created: ' + bar.created_at.to_s: 'Updated: ' + bar.updated_at.to_s %></td>
              <td>
              <input class="promobar_switcher header" id=<%="#{bar.id}"%> type="checkbox" <%= !bar.promobar_show ? "" : "checked" %> />
              </td>
            </tr>
          <% end %>
    
          <% @headers_off.each_with_index do |bar, i| %>
            <tr class="<%= bar.promobar_show ? "on" : "off" %>">
              <td>
                <a href="#" class="up">Up</a>
                <a href="#" class="down">Down</a>
              </td>
              <td class="order_number<%= bar.id %> order">-</td>
              <td><%= link_to bar.name, edit_promobar_path(bar, :shop_domain => params[:shop]) %></td>
              <td><%= render html: bar.text.html_safe %></td>
              <td><%= bar.button_on ? "YES" : "NO"%></td>
              <td><%= bar.subheader.promobar_show ? "YES" : "NO" unless bar.subheader.nil? %></td> 
              <td ><%= bar.updated_at == bar.created_at ? 'Created: ' + bar.created_at.to_s: 'Updated: ' + bar.updated_at.to_s %></td>
              <td>
              <input class="promobar_switcher header" id=<%="#{bar.id}"%> type="checkbox" <%= !bar.promobar_show ? "" : "checked" %> />
              </td>
            </tr>
          <% end %>
    
          <% unless @promobars.where(bar_type: 1).any? %>
              <tr>
                <td colspan="7">No header banners found.</td>
              </tr>
          <% end %>
    
          </tbody>
        </table>
    
        <table class="table table-bordered table-striped table-hover footers-table" style="text-align:center;">
          <caption style="text-align:center;">
            FOOTER BANNERS
          </caption>
          <thead>
          <tr>
            <th></th>
            <th>ORDER NUMBER</th>
            <th>BAR TITLE</th>
            <th>BAR TEXT</th>
            <th>BUTTON</th>
            <th>DATE</th>
            <th>ON/OFF</th>
          </tr>
          </thead>
    
          <tbody>
          <% @footers_on.each_with_index do |bar, i| %>
            <tr class="<%= bar.promobar_show ? "on" : "off" %>">
              <td>
                <a href="#" class="up">Up</a>
                <a href="#" class="down">Down</a>
              </td>
              <td class="order_number<%= bar.id %> order"><%= bar.order_number  %></td>
              <td><%= link_to bar.name, edit_promobar_path(bar, :shop_domain => params[:shop]) %></td>
              <td><%= render html: bar.text.html_safe %></td>
              <td><%= bar.button_on ? "YES" : "NO"%></td>
              <td ><%= bar.updated_at == bar.created_at ? 'Created: ' + bar.created_at.to_s: 'Updated: ' + bar.updated_at.to_s %></td>
              <td>
              <input class="promobar_switcher footer" id=<%="#{bar.id}"%> type="checkbox" <%= !bar.promobar_show ? "" : "checked" %> />
              </td>
            </tr>
          <% end %>
    
          <% @footers_off.each_with_index do |bar, i| %>
            <tr class="<%= bar.promobar_show ? "on" : "off" %>">
              <td>
                <a href="#" class="up">Up</a>
                <a href="#" class="down">Down</a>
              </td>
              <td class="order_number<%= bar.id %> order">-</td>
              <td><%= link_to bar.name, edit_promobar_path(bar, :shop_domain => params[:shop]) %></td>
              <td><%= render html: bar.text.html_safe %></td>
              <td><%= bar.button_on ? "YES" : "NO"%></td>
              <td ><%= bar.updated_at == bar.created_at ? 'Created: ' + bar.created_at.to_s: 'Updated: ' + bar.updated_at.to_s %></td>
              <td>
              <input class="promobar_switcher footer" id=<%="#{bar.id}"%> type="checkbox" <%= !bar.promobar_show ? "" : "checked" %> />
              </td>
            </tr>
          <% end %>
    
          <% unless @promobars.where(bar_type: 2).any? %>
              <tr>
                <td colspan="7">No footer banners found.</td>
              </tr>
          <% end %>
    
          </tbody>
        </table>
    
        <%= link_to 'ADD ANOTHER BANNER', new_promobar_path(:shop_domain => params[:shop]), class: 'btn btn-primary' %>
        <input type="button" value="Save banners order" class="btn btn-success" onclick="saveBannerOrder()">
      </div>
    </div>
  </div>
  
  <div id="tabs-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row lock_feature_form">
          <h3 class="text-center">Lock Feature Settings</h3>
          <div class="col-md-3 text-center">
            <div class="form-group">
              <label>Turn ON/OFF Lock Feature</label>
              <input type="checkbox" class="form-control lock_turned_on" <%= @lock.turned_on ? "checked" : "" %>>
            </div>
          </div>
          <div class="col-md-3 text-center">
            <div class="form-group">
              <label>Promobars background</label>
              <input type="text" class="form-control lock_color" value="<%= @lock.color %>">
            </div>
          </div>
          <div class="col-md-3 text-center">
            <div class="form-group">
              <label>Disable Transition Between Promobars</label>
              <input type="checkbox" class="form-control lock_disable_transition" <%= @lock.disable_transition ? "checked" : "" %>>
            </div>
          </div>
          <div class="col-md-3 text-center">
            <br>
            <button class="btn btn-info save_lock_feature">
              Save Lock Feature Parameters
            </button>
          </div>
        </div>
        <div class="global_promobar_settings row">
          <h3 class="text-center">Global Promobars Settings</h3>
          <div class="col-md-4">
            <div class="form-group">
              <label>Show promobars only on index page</label>
              <input type="checkbox" class="form-control only_on_index" <%= @only_on_index ? "checked" : "" %>>    
            </div>
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>
        